import { useEffect, useState } from 'react';
import { Card, FormField, Loader } from '../components';
import axios from 'axios';
import { Posts, RenderProps } from "../types"
import { motion } from 'framer-motion';


const RenderCards = ({ data, title }: RenderProps) => {
  if (data?.length > 0) {
    return (
      data.map((post) => <Card key={post.id} {...post} />)
    );
  }

  return (
    <h2 className="mt-5 font-bold text-[#6469ff] text-xl uppercase">{title}</h2>
  );
};



const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState<Posts>([{
    id: '',
    name: '',
    prompt: '',
    photo: '',
    blurData:'',
  }]);

  const [searchText, setSearchText] = useState('');
  const [searchResult, setSearchResult] = useState<Posts>([{
    id: '',
    name: '',
    prompt: '',
    photo: '',
    blurData:'',
  }])
   
   const [searchTimeout, setSearchTimeout] = useState<number>()
  



  const fetchPosts = async () => {
    const { data } = await axios.get('https://dall-e-image-generator-8csh.onrender.com/api/v1/post');
    if (data.success === true) {
      setAllPosts(data.data.reverse());
      setLoading(false);

    }
  }

  useEffect(() => {
    setLoading(true);
    try {

      fetchPosts()

    } catch (error) {
      alert(error);
      setLoading(false);

    }

  }, [])

  const handleSearch=(e:React.ChangeEvent<HTMLInputElement>)=>
  {

      clearTimeout(searchTimeout);
      setSearchText(e.target.value);

      setSearchTimeout(
          setTimeout(() => {
            const SearchResult=allPosts.filter((item)=>item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));

            setSearchResult(SearchResult);
        }, 500)
      );
    
  }



  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>The Community Showcase</h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
      </div>

      <div className="mt-16">
        <FormField
            labelName='Search'        
            type='text'
            name='search'
            placeholder='Search posts'
            value={searchText}
            handleChange={handleSearch} 
        />
      </div>

      <div className='mt-10'>
        {loading ? (
          <div className='flex justify-center items-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText &&
              <h2 className="font-medium text-[#666e75] text-xl mb-3">
                Showing Results for <span className="text-[#222328]">{searchText}</span>:
              </h2>
            }

            <motion.div layout className="grid  lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchResult}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No Posts Exist Yet"
                />
              )}
            </motion.div>
          </>
        )}
      </div>
    </section>
  );
}

export default Home;
